# Site
repository: fhkingma/modern-resume-theme
favicon: images/favicon.ico

# Personal info
name: Friso H. Kingma
title: Data Scientist
email: fhkingma@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  fhkingma
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: friso-kingma-b94496a0
# pinterest_username: jekyll
youtube_username: UCoKqCMaGUF5jj0WDC506Y7Q
# googleplus_username: +jekyll

# About Section
#about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I recently graduated from the Erasmus University Rotterdam obtaining a Master of Science (M.Sc.) degree in Econometrics and Management Science. The master’s track I have undertaken was Operations Research & Quantitative Logistics. For my master’s thesis, I was advised by Michel van de Velden. For the related research, I visited Berkeley Artificial Intelligence Research lab (BAIR), where I was advised by Pieter Abbeel. I have a Bachelor of Science (B.Sc.) degree in Industrial and Applied Mathematics from Delft University of Technology. For my bachelor’s thesis, I was advised by both Marco Loog and Frank van der Meulen.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
theme: modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
