# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Personal info
name: Friso H. Kingma
title: Data Scientist
email: fhkingma@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
github_username:  fhkingma
linkedin_username: friso-kingma-b94496a0

additional_links:
- title: Google Scholar
  icon: fa-google
  url: https://scholar.google.com/citations?user=mVk7QmUAAAAJ
- title: Youtube Channel
  icon: fa-youtube
  url: https://www.youtube.com/channel/UCoKqCMaGUF5jj0WDC506Y7Q

# About Section
#about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Data Scientist at [Adyen](https://www.adyen.com/). Before joining Adyen, I was involved in a machine learning research project in collaboration with [Tom Bird](https://www.linkedin.com/in/thomas-bird-b101a75a/) and [David Barber](http://web4.cs.ucl.ac.uk/staff/D.Barber/pmwiki/pmwiki.php) from the [UCL Centre of Artificial Intelligence](https://www.ucl.ac.uk/ai-centre/). I graduated from the Erasmus University Rotterdam obtaining a Master of Science (M.Sc.) degree in Econometrics and Management Science. The master’s track I have undertaken was Operations Research & Quantitative Logistics. For my master’s thesis, I was advised by [Michel van de Velden](https://www.eur.nl/people/michel-van-de-velden). For the related research, I visited Berkeley Artificial Intelligence Research lab ([BAIR](https://bair.berkeley.edu/)), where I was advised by [Pieter Abbeel](https://people.eecs.berkeley.edu/~pabbeel/) and [Jonathan Ho](http://www.jonathanho.me/). I have a Bachelor of Science (B.Sc.) degree in Industrial and Applied Mathematics from Delft University of Technology. For my bachelor’s thesis, I was advised by both [Marco Loog](https://scholar.google.nl/citations?user=2gmHmJYAAAAJ) and [Frank van der Meulen](https://scholar.google.nl/citations?user=oHglcfAAAAAJ).

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
